services:

  mongo:
    build:
      context: .
      dockerfile: docker/DB/Dockerfile
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend_stream:
    build:
      context: .
      dockerfile: docker/backend_stream/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./scripts:/app/scripts
      - ./model:/app/model
    environment:
      - MONGO_URL=mongodb://mongo:27017/
      - TZ=Europe/Moscow
    depends_on:
      - mongo

  backend_server:
    build:
      context: .
      dockerfile: docker/backend_server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./scripts:/app/scripts
      - ./model:/app/model
    environment:
      - MONGO_URL=mongodb://mongo:27017/
      - TZ=Europe/Moscow
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "5500:5500"
    volumes:
      - ./scripts/UI/frontend:/app/frontend
      - ./icons:/app/frontend/icons

  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017/
      - DB_NAME=audiototext_tests
      - TZ=Europe/Moscow
    depends_on:
      - mongo
    profiles:
      - testing

volumes:
  mongo_data: